### ISSUE TITLE
打包到ios真机，好多组件点击导致应用闪退❗❗❗

### ISSUE THREAD

**Issue by mxismean** [toly1994328/FlutterUnit#1]
大佬还是大佬啊，太牛逼了 👍
flutter初学者的天堂，感谢万分👍

不过还有一些闪退的问题，还望大佬闲暇之余处理一下 👍

持续 关注

**Comment by toly1994328** [comment]
好，我主要是搞Android的，iOS每太上心

**Comment by mxismean** [comment]
👍👍👍 感谢

**Comment by toly1994328** [comment]
已fix

**Comment by mxismean** [comment]
👍迫不及待打新包了

**Comment by WhiteCjy** [comment]
Running Xcode build...
Xcode build done.                                           10.7s
Failed to build iOS app
Error output from Xcode build:
↳
    2021-09-26 15:04:56.077 xcodebuild[85287:6640135] CFURLRequestSetHTTPCookieStorageAcceptPolicy_block_invoke: no longer implemented and should not be called
    ** BUILD FAILED **


Xcode's output:
↳
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Analyzing workspace
    note: Constructing build description
    note: Build preparation complete
    /Users/cjy/StudioProjects/FlutterUnit/ios/Pods/Pods.xcodeproj: warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.5.99. (in target 'Pods-Runner' from project 'Pods')
运行到真机出错
