### ISSUE TITLE
iOS 点击pageview sql语句传的数组为[]奔溃问题  SELECT * FROM widget WHERE id in (?) 

### ISSUE THREAD

**Issue by WolfAloneLJ** [toly1994328/FlutterUnit#10]
widgetId怎么设置的，怎么匹配到flutter.db的呢？iOS 点击pageview sql语句传的数组为[]

**Comment by vicxia** [comment]
按照这个PullRequest可以修复这个问题
https://github.com/toly1994328/FlutterUnit/pull/17

**Comment by toly1994328** [comment]
OK，可行，谢啦
