### ISSUE TITLE
web端在微信浏览器中打开样式会乱

### ISSUE THREAD

**Issue by qianbaibudu** [toly1994328/FlutterUnit#103]
如同标题所言，微信浏览器中打开

![944b71194b795b311db1e00bf1b7cab](https://user-images.githubusercontent.com/64069776/202204236-509d52d3-5e20-4434-83d3-1c6021b212cd.jpg)
![3467bdb2fe3274e1d278d21b388def0](https://user-images.githubusercontent.com/64069776/202204247-9b092892-895a-4d80-9c6a-45d646af4601.jpg)
这要怎么解决呢

**Comment by toly1994328** [comment]
web 能跑就行，暂没时间适配

**Comment by qianbaibudu** [comment]
在我自己的项目中，发现是因为微信字体大小问题导致的
解决办法：在index.html禁用了微信浏览器设置字体大小问题
