### ISSUE TITLE
android运行一直卡在启动页

### ISSUE THREAD

**Issue by Witnin** [toly1994328/FlutterUnit#105]
I/flutter ( 4225): ====数据库所在文件夹: /data/user/0/com.toly1994.flutter_unit/databases=======
I/flutter ( 4225): =====flutter.db==== assets ======拷贝完成====
I/flutter ( 4225): ====数据库所在文件夹: /data/user/0/com.toly1994.flutter_unit/databases=======
I/flutter ( 4225): 初始化数据库....
D/Surface ( 4225): Surface::disconnect(this=0x7bbeefa000,api=1)
D/Surface ( 4225): Surface::disconnect(this=0x7bbeefa000,api=-1)
D/Surface ( 4225): Surface::disconnect(this=0x7ca85c7000,api=1)
I/GED     ( 4225): ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 2, oppidx_max 2, oppidx_min 0
V/PhoneWindow( 4225): DecorView setVisiblity: visibility = 4, Parent = android.view.ViewRootImpl@aec7fdc, this = DecorView@5cfa8e5[MainActivity]
V/PhoneWindow( 4225): DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@aec7fdc, this = DecorView@5cfa8e5[MainActivity]
E/GraphicExt( 4225): GraphicExtModuleLoader::CreateGraphicExtInstance false
D/Surface ( 4225): Surface::connect(this=0x7bbeef9000,api=1)
D/Surface ( 4225): Surface::setBufferCount(this=0x7bbeef9000,bufferCount=3)
E/GraphicExt( 4225): GraphicExtModuleLoader::CreateGraphicExtInstance false
E/GraphicExt( 4225): GraphicExtModuleLoader::CreateGraphicExtInstance false
D/Surface ( 4225): Surface::connect(this=0x7c122fb000,api=1)
D/Surface ( 4225): Surface::disconnect(this=0x7c122fb000,api=1)
D/Surface ( 4225): Surface::disconnect(this=0x7c122fb000,api=-1)
D/Surface ( 4225): Surface::disconnect(this=0x7bbeef9000,api=1)
I/GED     ( 4225): ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 2, oppidx_max 2, oppidx_min 0
V/PhoneWindow( 4225): DecorView setVisiblity: visibility = 4, Parent = android.view.ViewRootImpl@aec7fdc, this = DecorView@5cfa8e5[MainActivity]

**Comment by toly1994328** [comment]
非项目问题
