### ISSUE TITLE
win11运行项目只能到启动页

### ISSUE THREAD

**Issue by ertchen** [toly1994328/FlutterUnit#106]
下载代码到本地，不做任何更改，运行项目，到启动页，不能继续跳转，更换win10电脑可以正常运行。

**Comment by toly1994328** [comment]
我 win11 没什么问题，有什么日志

**Comment by ertchen** [comment]
我win11笔记本运行就是卡在这里，我不是程序员，不知道在哪里看日志







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "toly1994328/FlutterUnit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月28日(星期一) 下午3:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [toly1994328/FlutterUnit] win11运行项目只能到启动页 (Issue #106)





 
我 win11 没什么问题，有什么日志

**Comment by chuhouyi** [comment]
你可以在闪频页把_minCost值改大一点

**Comment by ertchen** [comment]
非常感谢，将_minCost值改到2500成功启动了。







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "toly1994328/FlutterUnit"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月30日(星期一) 下午5:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [toly1994328/FlutterUnit] win11运行项目只能到启动页 (Issue #106)





 
你可以在闪频页把_minCost值改大一点

**Comment by toly1994328** [comment]
排查了，代码处理逻辑一些问题，已修正。
