### ISSUE TITLE
macos 版本 点击范围很小 比如图标 你只能点击图标体 点击图标透明位置都无法点击

### ISSUE THREAD

**Issue by xiaoyi510** [toly1994328/FlutterUnit#107]
macos 版本 点击范围很小 比如图标 你只能点击图标体 点击图标透明位置都无法点击

下面这种 我点击颜色无法弹出 只有点中那个文字很近才有效果
![image](https://user-images.githubusercontent.com/20254874/205571335-564666be-873c-41dd-aae9-b7667c99aecb.png)

![image](https://user-images.githubusercontent.com/20254874/205571623-193c3304-abf6-42c5-8063-bf14d332b17b.png)

点击返回这种也很难返回

**Comment by toly1994328** [comment]
桌面版界面已优化
