### ISSUE TITLE
Could not find a file named "pubspec.yaml" in app_update

### ISSUE THREAD

**Issue by Mamong** [toly1994328/FlutterUnit#108]
Could not find a file named "pubspec.yaml" in "/Users/xxx/Documents/FlutterUnit/packages/app_update".

Android Studio Electric Eel | 2022.1.1

Flutter 3.3.10 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 135454af32 (6 weeks ago) • 2022-12-15 07:36:55 -0800
Engine • revision 3316dd8728
Tools • Dart 2.18.6 • DevTools 2.15.0

**Comment by parade0393** [comment]
the same question

**Comment by parade0393** [comment]
same question

**Comment by toly1994328** [comment]
有点文件忘提交了，已处理
