### ISSUE TITLE
Desktop端在软件运行时会先闪出原Flutter窗口再加载软件主窗口

### ISSUE THREAD

**Issue by wpbkj** [toly1994328/FlutterUnit#110]
## 问题原因
使用``window_manager``但没有修改相关文件
### Windows
https://github.com/toly1994328/FlutterUnit/blob/a988e8e7ffb84143decb9257cf1c6cdbc0f0abcd/windows/runner/win32_window.cpp#L120
### Linux
https://github.com/toly1994328/FlutterUnit/blob/a988e8e7ffb84143decb9257cf1c6cdbc0f0abcd/linux/my_application.cc#L51
### macOS
https://github.com/toly1994328/FlutterUnit/blob/a988e8e7ffb84143decb9257cf1c6cdbc0f0abcd/macos/Runner/MainFlutterWindow.swift
## 参考
https://github.com/leanflutter/window_manager/blob/main/README-ZH.md#%E5%9C%A8%E5%90%AF%E5%8A%A8%E6%97%B6%E9%9A%90%E8%97%8F

**Comment by wpbkj** [comment]
根据文档修改了相关文件，并已提交pr

**Comment by toly1994328** [comment]
感谢指出，已修改~
