### ISSUE TITLE
在【收藏集录】中点击组件 BlocProvider.of() 提示异常

### ISSUE THREAD

**Issue by Li-00** [toly1994328/FlutterUnit#117]
```
class CategoryShow {
//
_toDetailPage(BuildContext context, WidgetModel model) async {
    BlocProvider.of<WidgetDetailBloc>(context).add(FetchWidgetDetail(model));
    Navigator.pushNamed(context, UnitRouter.widget_detail, arguments: model);
  }
//
}

```

BlocProvider.of() called with a context that does not contain a WidgetDetailBloc.
        No ancestor could be found starting from the context that was passed to BlocProvider.of<WidgetDetailBloc>().
This can happen if the context you used comes from a widget above the BlocProvider. The context used was: SliverList(delegate: SliverChildBuilderDelegate#bbcaa(estimated child count: 19), renderObject: 
RenderSliverList#f3656 relayoutBoundary=up2)
![image](https://user-images.githubusercontent.com/71139000/233785111-4e9e3009-fd24-47be-876f-a026f4fa66b5.png)

错误提示是因为您在使用 BlocProvider.of<WidgetDetailBloc>(context) 获取 WidgetDetailBloc 时，传入的 context 没有包含该 Bloc 的 Provider，导致无法获取到该 Bloc。这可能是因为您传入的 context 是来自于一个 BlocProvider 的父级组件，而不是该 BlocProvider 的子级组件。请检查一下 BlocProvider 是否正确包裹在该组件中。

解决方案如下:
1. 确保已为App或MaterialApp设置包裹WidgetDetailBloc的BlocProvider。如:
dart
void main() {
  BlocProvider<WidgetDetailBloc>.value(
    value: WidgetDetailBloc(),
    child: App(),
  ); 
}

**Comment by Li-00** [comment]
![image](https://user-images.githubusercontent.com/71139000/233785220-1fa7acd9-88b5-4a43-8425-b3b31ae6b949.png)

**Comment by toly1994328** [comment]
你这版本很老了，早就已经处理了，更新即可

**Comment by Li-00** [comment]
大佬，我是拉取的 master 分支，编译环境 flutter 3.7.0， Windows 10 因特尔处理器，看了 git log 代码是 master 最新，flutter 3.7 以上运行 yaml 提示版本过高，因此你指的版本老是代码还是环境，盼回复

**Comment by toly1994328** [comment]
刚更新 Flutter 3.7.12 ，没有问题。 应该是代码老，我这运行没问题

**Comment by Li-00** [comment]
好的，这个周末我再看看，感谢大佬回复
