### ISSUE TITLE
Xcode 14.3，Flutter 3.10.0，iOS & macOS ，error：lib/arc/libarclite_iphonesimulator.a not found

### ISSUE THREAD

**Issue by maxlee12** [toly1994328/FlutterUnit#120]
Error (Xcode): File not found: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/arc/libarclite_iphonesimulator.a

**Comment by Ignacio1110** [comment]
可以嘗試改Podfile

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
  end
end

相關連結 https://stackoverflow.com/questions/75574268/missing-file-libarclite-iphoneos-a-xcode-14-3
