### ISSUE TITLE
运行报错  dlopen failed: library "libflutter.so" not found

### ISSUE THREAD

**Issue by JuYiYang** [toly1994328/FlutterUnit#123]
1. flutter pub get
2. flutter run 
3.  dlopen failed: library "libflutter.so" not found
4. 
![image](https://github.com/toly1994328/FlutterUnit/assets/107595466/da0e80d4-8d22-4bf9-81e0-45cbcdbd8323)

**Comment by toly1994328** [comment]
环境问题，新建项目看看

**Comment by JuYiYang** [comment]
> 环境问题，新建项目看看

是环境的问题，我忘记回来关了，之前我新建了个项目，把你代码移进去就OK了
