### ISSUE TITLE
mac win 版本下载链接无效

### ISSUE THREAD

**Issue by m1codex** [toly1994328/FlutterUnit#124]
wget http://toly1994.com/file/flutter_unit_mac.zip
--2023-08-23 16:29:51--  http://toly1994.com/file/flutter_unit_mac.zip
正在解析主机 toly1994.com (toly1994.com)... 119.45.173.197
正在连接 toly1994.com (toly1994.com)|119.45.173.197|:80... 已连接。
已发出 HTTP 请求，正在等待回应... 读取文件头错误 (Connection reset by peer)。
重试中。

**Comment by toly1994328** [comment]
服务器到期了，现在已将下载地址改到 github release 了
