### ISSUE TITLE
桌面平台左侧菜单相互切换，导致页面重新加载

### ISSUE THREAD

**Issue by melancholyboy** [toly1994328/FlutterUnit#134]
桌面平台左侧菜单相互切换，导致页面重新加载，go_router导航所致，但是需要怎么处理呢

**Comment by toly1994328** [comment]
为什么不能重新加载？切换后销毁不需要的界面，也没有什么问题。希望保持活性，可以参考 go_router 相关特性。此处设计使然，不影响使用
