### ISSUE TITLE
为什么clone之后不能运行？ 

### ISSUE THREAD

**Issue by oldwai** [toly1994328/FlutterUnit#138]
<img width="602" alt="截屏2024-05-25 19 25 11" src="https://github.com/toly1994328/FlutterUnit/assets/22065921/730a08c1-34f9-4af8-b524-14109b3fa688">
clone master分支 使用flutter版本如下
Flutter 3.19.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision bae5e49bc2 (3 months ago) • 2024-02-13 17:46:18 -0800
Engine • revision 04817c99c9
Tools • Dart 3.3.0 • DevTools 2.31.1
无法运行
使用3.19.6会提示
Because every version of widgets from path depends on intl ^0.19.0 and every version of flutter_localizations from sdk depends on intl 0.18.1, widgets from path is   incompatible with flutter_localizations from sdk. So, because flutter_unit depends on bot
因为将依赖包降为0.18.1后还是无法运行

**Comment by toly1994328** [comment]
目前项目运行版本： Flutter 3.22.0
