### ISSUE TITLE
Window11 打开exe报错

### ISSUE THREAD

**Issue by Terence-eng** [toly1994328/FlutterUnit#141]
![Uploading 20240702-173210.jpeg…]()

**Comment by Terence-eng** [comment]
![20240702-173210](https://github.com/toly1994328/FlutterUnit/assets/24852155/1b4b81a1-a9f1-4959-9913-779ced3f9d1a)

**Comment by toly1994328** [comment]
非软件问题，有些电脑系统可能缺失这个，搜一下可以知道解决方案
