### ISSUE TITLE
【BUG】试用反馈

### ISSUE THREAD

**Issue by xiebaofu** [toly1994328/FlutterUnit#146]
v3.0.0试用下来发现有三个问题：
1、在【知识集锦】点击布局总览时`display_logic.dart` line-27 会报 `_TypeError (Null check operator used on a null value)`异常
2、在【工具宝箱】选择压缩包弹窗后点击【取消】按钮，`issues_api.dart` line-20，157 会报一个`信号灯超时时间已到`的异常，非必现
![image](https://github.com/user-attachments/assets/b5051c63-a1f1-43f8-aa37-0d0e1d6eab64)
3、暗黑模式下【组件集录】中的组件详情，有部分内容字体较浅，看不清

**Comment by toly1994328** [comment]
小问题，已处理
