### ISSUE TITLE
二维码下载下来的安装包没有apk后缀，导致下载下来没法直接安装。

### ISSUE THREAD

**Issue by LvJson** [toly1994328/FlutterUnit#19]

**Comment by toly1994328** [comment]
重命名不会？

**Comment by LvJson** [comment]
我只是好心提醒你，没必要设此门槛麻烦使用者。
本来扫码直接下载就可以的事情，我还要再多此一举去重命名。
都是做开发的，简单明了的道理你我都懂。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "张风捷特烈"<notifications@github.com&gt;; 
发送时间: 2020年5月6日(星期三) 下午3:33
收件人: "toly1994328/FlutterUnit"<FlutterUnit@noreply.github.com&gt;; 
抄送: "↓海＞↑＜海↓"<571260259@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [toly1994328/FlutterUnit] 二维码下载下来的安装包没有apk后缀，导致下载下来没法直接安装。 (#19)





 
重命名不会？

**Comment by toly1994328** [comment]
好吧，谢谢你的提醒。我也想啊，但有.apk结尾的链接，微信扫的时候扫不出来。

**Comment by LvJson** [comment]
做开发的一般都知道微信是不支持下载和安装外部apk的，所以都会用浏览器扫描下载。
加后缀只是我的建议，你依然可以坚持你的想法。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "张风捷特烈"<notifications@github.com&gt;; 
发送时间: 2020年5月6日(星期三) 下午3:46
收件人: "toly1994328/FlutterUnit"<FlutterUnit@noreply.github.com&gt;; 
抄送: "↓海＞↑＜海↓"<571260259@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [toly1994328/FlutterUnit] 二维码下载下来的安装包没有apk后缀，导致下载下来没法直接安装。 (#19)





 
好吧，谢谢你的提醒。我也想啊，但有.apk结尾的链接，微信扫的时候扫不出来。
