### ISSUE TITLE
Cons是什么？

### ISSUE THREAD

**Issue by yinzelin627** [toly1994328/FlutterUnit#40]
在基础组建库中m
 decoration: BoxDecoration(
        //添加渐变色
          gradient: LinearGradient(
              stops: stops,
              colors: Cons.rainbow.map((e) => Color(e)).toList()),
          borderRadius: BorderRadius.only(
              topLeft: Radius.circular(50),
              bottomRight: Radius.circular(50)),
          boxShadow: [
            BoxShadow(
                color: Colors.grey,
                offset: Offset(1, 1),
                blurRadius: 10,
                spreadRadius: 1),
          ]),
其中Cons是什么？我的版本是1.17.1

**Comment by toly1994328** [comment]
你应该下载新版本，Cons是以前弄得常量管理类， 现在不了。
