### ISSUE TITLE
源码clone下来widgets目录底下有自定义view和某些属性缺失

### ISSUE THREAD

**Issue by yuyuxingchen** [toly1994328/FlutterUnit#56]
* Other/RawImage/node1_base.dart  #53行 RawImage-->isAntiAlias
* StatefulWidget/InteractiveViewer/node1_base.dart #30行 -->InteractiveViewer
* StatefulWidget/InteractiveViewer/node2_constrained.dart #23行 -->InteractiveViewer
* StatefulWidget/InteractiveViewer/node3_controller.dart #23行 -->TransformationController

**Comment by toly1994328** [comment]
版本

**Comment by yuyuxingchen** [comment]
> 版本

Master分支下面的最新代码

**Comment by toly1994328** [comment]
我说Flutter版本😅
