### ISSUE TITLE
发现一个Web端TextField的缺陷，复现步骤如下：

### ISSUE THREAD

**Issue by yaochangliang159** [toly1994328/FlutterUnit#65]
1.谷歌浏览器打开项目网址：http://toly1994328.gitee.io/flutter_web/#/
2.点击上方的“stful”红色菜单
3.点击“TextField”菜单
4.滚动页面到最底部，看到了“decoration的复杂菜单”示例，然后往页面的textfield输入东西，整个页面都会卡死，不管点击哪个地方都会没反应，除非重新刷新网页。
但是在手机端是好着的，就是在网页端才会有这个问题

**Comment by li-xiaojun** [comment]
确实会卡死，我试了最新版也会卡死，
