### ISSUE TITLE
flutter run -d windows report following

### ISSUE THREAD

**Issue by skydig** [toly1994328/FlutterUnit#67]
Launching lib\main.dart on Windows in debug mode...
CMake Error at flutter/generated_plugins.cmake:14 (add_subdirectory):
  The source directory

    C:/Users/ssyp/flutter_unit/windows/flutter/ephemeral/.plugin_symlinks/path_provider_fde/windows

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:51 (include)

CMake Error at flutter/generated_plugins.cmake:14 (add_subdirectory):
  The source directory

    C:/Users/ssyp/flutter_unit/windows/flutter/ephemeral/.plugin_symlinks/url_launcher_fde/windows

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:51 (include)

CMake Error at flutter/generated_plugins.cmake:14 (add_subdirectory):
  The source directory

    C:/Users/ssyp/flutter_unit/windows/flutter/ephemeral/.plugin_symlinks/window_size/windows

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:51 (include)

**Comment by skydig** [comment]
Launching lib\main.dart on Windows in debug mode...
CMake Error at flutter/generated_plugins.cmake:14 (add_subdirectory):
  The source directory

    C:/Users/ssyp/flutter_unit/windows/flutter/ephemeral/.plugin_symlinks/path_provider_fde/windows

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:51 (include)


CMake Error at flutter/generated_plugins.cmake:14 (add_subdirectory):
  The source directory

    C:/Users/ssyp/flutter_unit/windows/flutter/ephemeral/.plugin_symlinks/url_launcher_fde/windows

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:51 (include)


CMake Error at flutter/generated_plugins.cmake:14 (add_subdirectory):
  The source directory

    C:/Users/ssyp/flutter_unit/windows/flutter/ephemeral/.plugin_symlinks/window_size/windows

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:51 (include)

**Comment by toly1994328** [comment]
代码中 windows 版本比较旧，后面会和Mac版本合并。
