### ISSUE TITLE
红米8A,安装失败

### ISSUE THREAD

**Issue by LittleTadpole** [toly1994328/FlutterUnit#7]
正好在学习flutter,感谢大佬.打算体验安装,结果安装失败. 手机提示.失败原因: 其它原因.

**Comment by toly1994328** [comment]
目前只打包了v8 ,你可以下载项目运行一下

**Comment by LittleTadpole** [comment]
> 目前只打包了v8 ,你可以下载项目运行一下

好的,大佬,我已经在运行了哈.多谢开源学习
