### ISSUE TITLE
具体安装使用步骤

### ISSUE THREAD

**Issue by PhoenixLeeSin** [toly1994328/FlutterUnit#71]
大佬可以给一个具体安装使用步骤吗？mac下载完项目执行完flutter pub get还是缺失文件，不知道是flutter版本问题还是其他

**Comment by toly1994328** [comment]
先重启一下，如果还出错，Flutter 版本，错误图片看看。

**Comment by PhoenixLeeSin** [comment]
1. clone完该项目，执行完flutter pub get后如果出现项目内文件报错基本可以确实为flutter版本问题，执行 flutter upgrade v1.22.5即可
2. mac 下 使用AS或者VS 跑ios模拟器均长时间未成功，貌似在下载啥东西，具体未知 一会解决了会更新
![image](https://user-images.githubusercontent.com/20637153/104142518-eb51d100-53f6-11eb-997f-e99449476426.png)
3.  @toly1994328   谢谢大佬答疑，建议把一些常见的问题放到read.me中
