### ISSUE TITLE
WidgetsFlutterBinding.ensureInitialized();这句代码作用是啥 

### ISSUE THREAD

**Issue by lianshuoshuo** [toly1994328/FlutterUnit#74]
大佬 
WidgetsFlutterBinding.ensureInitialized()；的作用是啥 不太明白

**Comment by shexm** [comment]
先实例化WidgetsFlutterBinding，不然要到调用runApp才实例化WidgetsFlutterBinding，WidgetsFlutterBinding没有实例化就没有GestureBinding.instance。
