### ISSUE TITLE
[!] Invalid `Podfile` file:

### ISSUE THREAD

**Issue by GarthGit** [toly1994328/FlutterUnit#81]
[!] Invalid `Podfile` file: /Users/FlutterUnit-master/ios/Flutter/Generated.xcconfig must exist. If you're running pod install manually, make sure flutter pub get is executed first.

**Comment by toly1994328** [comment]
Generated.xcconfig is a generated file ,it should be auto create when build project

![image](https://user-images.githubusercontent.com/26687012/123934359-c9a8ce00-d9c5-11eb-8561-711437375b9b.png)
