### ISSUE TITLE
Mac 端下载后尝试浏览，点击组件不灵敏

### ISSUE THREAD

**Issue by zeqinjie** [toly1994328/FlutterUnit#88]
![image](https://user-images.githubusercontent.com/8444646/142726414-7b07e8f0-f721-4dd9-ac0d-52e048c0a38d.png)
问题如题

**Comment by tesla-wu** [comment]
mac 上运行软件，操作起来特别不顺，点击半天没响应

**Comment by toly1994328** [comment]
之前挺好的，现在确实是，可能是曾经构建的flutter版本太低，macos 升级后导致的。现在重新构建了一下，已经没问题了，可以重新下载体验 ~
