### ISSUE TITLE
代码编译报错，我猜是Flutter版本问题

### ISSUE THREAD

**Issue by kanglongba** [toly1994328/FlutterUnit#91]
我的Flutter是2.8.0，编译出错的文件是：node1_base.dart 和 node2_base.dart。需要稍作修改，才能编译：
![image](https://user-images.githubusercontent.com/1843247/145773598-7b0354c4-a733-427a-8d0c-2c2b577e6ab3.png)

**Comment by toly1994328** [comment]
建议更新到最新稳定版，运行 flutterunit
